<?php

namespace APIBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends DocumentRepository
{

    public function getLastStatistic()
    {
        return $this->createQueryBuilder()
            ->field('id')
            ->sort('created', 'DESC')
            ->popFirst()
            ->getQuery()
            ->getSingleResult();
    }
}
